name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - move-to-github-actions

env:
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    name: Tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1
          - 8.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
            composer-options: --optimize-autoloader --no-interaction

      - name: Run tests
        run: make tests

  rusty:
    name: Rusty on PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1
          - 8.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
            composer-options: --optimize-autoloader --no-interaction

      - name: Run Rusty
        run: make rusty
